# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8f414a6014da5d5f86e421cafee05e7fd3b1b681f392dd0e3b6f505c4b1615878c108a0202a97aa3ecc078b9a03cbce0b5e567d92a999f65612b111454a95ad

test:
  secret_key_base: c8777b3c862227d19568ab913e7f0fad895030371602e9d9ca9739f5f808fc7dff9289d406efefbc5c5c3ea5b3d73d46e42af27431ac2f8ac6b3ddf8aa40f0b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
